MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce: @ 82C6E05
	.string "I will take your Heart Scale\n"
	.string "for this. Is that okay?$"

MoveTutor_Text_SwaggerTeach: @ 82C6E37
	.string "Heh! My Pokémon totally rules!\n"
	.string "It's cooler than any Pokémon!\p"
	.string "I was lipping off with a swagger in\n"
	.string "my step like that when the Chairman\l"
	.string "chewed me out.\p"
	.string "That took the swagger out of my step.\p"
	.string "If you'd like, I'll teach the move\n"
	.string "Swagger to a Pokémon of yours.\l"
	.string "In exchange of a Heart Scale.$"

MoveTutor_Text_SwaggerDeclined: @ 82C6F33
	.string "What, no? Can't you get into\n"
	.string "the spirit of things?$"

MoveTutor_Text_SwaggerWhichMon: @ 82C6F66
	.string "All right, which Pokémon wants to\n"
	.string "learn how to Swagger?$"

MoveTutor_Text_SwaggerTaught: @ 82C6F9E
	.string "I'll just praise my Pokémon from now\n"
	.string "on without the swagger.$"

MoveTutor_Text_PsychicFangsTeach: @ 82C6FDB
    	.string "Did you know that with enough\n"
    	.string "willpower, you can chew through\n"
    	.string "anything?\p"
    	.string "Take me for example, I was born\n"
    	.string "with no teeth, but I have honed my\n"
    	.string "psychic skill to use Psychic Fangs\l"
    	.string "to chew through anything.\p"
    	.string "Speaking of which, do you want me\n"
    	.string "to teach one of your Pokémon the\n"
    	.string "move Psychic Fangs?\p"
    	.string "But it'll cost you.$"

MoveTutor_Text_PsychicFangsDeclined: @ 82C70C4
    	.string "No matter.\n"
    	.string "You can come back later if you\n"
    	.string "change your mind.$"

MoveTutor_Text_PsychicFangsWhichMon: @ 82C70F3
    	.string "Alright then.\n"
    	.string "Which one of your Pokémon needs\n"
    	.string "a pair of psychic teeth?$"

MoveTutor_Text_PsychicFangsTaught: @ 82C7133
    	.string "Now your Pokémon wouldn't have any\n"
    	.string "trouble chewing through hard stuff.$"

MoveTutor_Text_CrunchTeach: @ 82C7174
    	.string "When life gives you teeth, you use\n"
    	.string "it to bite everything.\p"
    	.string "I use my teeth like I use my hand.\n"
    	.string "It made my teeth stronger, and I can\p"
    	.string "make your Pokémon's teeth stronger\n"
    	.string "with the move Crunch.\p"
    	.string "I can teach one of your Pokémon\n"
    	.string "Crunch for a Heart Scale.$"

MoveTutor_Text_CrunchDeclined: @ 82C7221
	.string "No?\n"
    	.string "Do you want your Pokémon to get\n"
    	.string "cavities?$"

MoveTutor_Text_CrunchWhichMon: @ 82C7243
	.string "Yes!\n"
	.string "Show me which Pokémon I should teach.$"

MoveTutor_Text_CrunchTaught: @ 82C726E
    	.string "Haha!\n"
    	.string "Now your Pokémon will never get\n"
    	.string "cavities.$"

MoveTutor_MimicTeach: @ 82C72B6
	.string "Ah, young one!\p"
	.string "I am also a young one, but I mimic\n"
	.string "the styles and speech of the elderly\l"
	.string "folks of this town.\p"
	.string "What do you say, young one?\n"
	.string "Would you agree to it if I were to\l"
	.string "offer to teach the move Mimic\l"
	.string "in exchange of a Heart Scale?.$"

MoveTutor_MimicDeclined: @ 82C737F
	.string "Oh, boo! I wanted to teach Mimic\n"
	.string "to your Pokémon!$"

MoveTutor_Text_MimicWhichMon: @ 82C73B1
	.string "Fwofwo! And so I shall!\n"
	.string "Let me see the Pokémon\l"
	.string "you wish me to teach.$"

MoveTutor_Text_MimicTaught: @ 82C73F6
	.string "Mimic is a move of great depth.\p"
	.string "Could you execute it to perfection\n"
	.string "as well as me…?$"

MoveTutor_Text_AuroraBeamTeach: @ 82C7449
    	.string "Interesting observation.\n"
    	.string "While researching the Aurora Borealis\l"
    	.string "up in the Galar region, I noticed that\p"
    	.string "certain Electric type Pokémon also\n"
    	.string "learn the move Aurora Beam.\p"
    	.string "Would you like me to teach that move\n"
    	.string "to one of your Pokémon?$"

MoveTutor_Text_AuroraBeamDeclined: @ 82C7556
	.string "Okay. I'll be here if you change\n"
	.string "your mind.$"

MoveTutor_Text_AuroraBeamWhichMon: @ 82C7582
	.string "Okay! I'll teach it!\n"
	.string "Which Pokémon should I teach?$"

MoveTutor_Text_AuroraBeamTaught: @ 82C75B5
    	.string "Excellent.\n"
    	.string "I hope this will help us into further\n"
    	.string "research on how certain Electric type\p"
    	.string "Pokémon adapt to cold climates.$"

MoveTutor_Text_SleepTalkTeach: @ 82C7637
	.string "Humph! My wife relies on Hidden\n"
	.string "Power to stay awake.\p"
	.string "She should just take a nap like I do,\n"
	.string "and Sleep Talk.\p"
	.string "I can teach your Pokémon how to\n"
	.string "Sleep Talk instead, For a cute\l"
	.string "Heart Scale. Interested?$"

MoveTutor_Text_SleepTalkDeclined: @ 82C76E2
	.string "Oh, fine, fine. You want to stay awake\n"
	.string "with Hidden Power, too…$"

MoveTutor_Text_SleepTalkWhichMon: @ 82C7721
	.string "Ah, an appreciative child!\n"
	.string "Which Pokémon should I teach?$"

MoveTutor_Text_SleepTalkTaught: @ 82C775A
	.string "I've never once gotten my wife's\n"
	.string "coin trick right.\p"
	.string "I would be happy if I got it right\n"
	.string "even as I Sleep Talk…$"

MoveTutor_Text_ZenHeadbuttTeach: @ 82C77C6
    	.string "Mind over matter Dr. Angelo.\n"
    	.string "Not a miracle...... a fact. A favorite\n"
    	.string "quote from my favorite movie\p"
    	.string "The Lawnmower Man.\n"
    	.string "I was so inspired by the character Jobe\n"
    	.string "that I banged my head on the wall\n"
    	.string "multiple times in the hopes of reaching\l"
    	.string "his level of intellect.\p"
    	.string "While I haven't got any result, but I\n"
    	.string "did learn how to teach your Pokémon\l"
    	.string "the move Zen Headbutt.\p"
    	.string "Should I teach this move to one of your\n"
    	.string "Pokémon?$"

MoveTutor_Text_ZenHeadbuttDeclined: @ 82C78D1
    	.string "So, you don't want me to teach this\n"
    	.string "move to your Pokémon?\p"
    	.string "You're denying them from reaching\n"
    	.string "their higher intellect.$"

MoveTutor_Text_ZenHeadbuttWhichMon: @ 82C7911
    	.string "Smart choice.\n"
    	.string "Which Pokémon do you want me to\n"
    	.string "unlock their higher intellectual\n"
    	.string "potential?$"

MoveTutor_Text_ZenHeadbuttTaught: @ 82C794B
    	.string "THIS UNIVERSE IS MINE!!!!!\n"
    	.string "I AM COB HERE!!!!$"

MoveTutor_Text_DynamicPunchTeach: @ 82C79A6
	.string "I can't do this anymore!\p"
	.string "It's utterly hopeless!\p"
	.string "I'm a Fighting-type Trainer,\n"
	.string "so I can't win at the Battle Tent\l"
	.string "no matter how hard I try!\p"
	.string "Argh! Punch! Punch! Punch!\n"
	.string "Punch! Punch! Punch!\p"
	.string "What, don't look at me that way!\n"
	.string "I'm only hitting the ground!\p"
	.string "Or do you want me to teach your\n"
	.string "Pokémon Dynamic Punch?, In\l"
	.string "Exchange of a Heart Scale$"

MoveTutor_Text_DynamicPunchDeclined: @ 82C7AD4
	.string "Darn! You're even making fun of me?\n"
	.string "Punch! Punch! Punch!$"

MoveTutor_Text_DynamicPunchWhichMon: @ 82C7B0D
	.string "What? You do? You're a good person!\n"
	.string "Which Pokémon should I teach?$"

MoveTutor_Text_DynamicPunchTaught: @ 82C7B4F
	.string "I want you to win at the Battle Tent\n"
	.string "using that DynamicPunch!$"

MoveTutor_Text_DoubleEdgeTeach: @ 82C7B8E
	.string "Sigh…\p"
	.string "Sootopolis's Gym Leader is really\n"
	.string "lovably admirable.\p"
	.string "But that also means I have many\n"
	.string "rivals for his attention.\p"
	.string "He's got appeal with a Double-Edge.\n"
	.string "I couldn't even catch his eye.\p"
	.string "Please, let me teach your Pokémon\n"
	.string "the move Double-Edge, in exchange\n"
	.string "of a Heart Scale!$"

MoveTutor_Text_DoubleEdgeDeclined: @ 82C7C7E
	.string "Oh…\n"
	.string "Even you rejected me…$"

MoveTutor_Text_DoubleEdgeWhichMon: @ 82C7C98
	.string "Okay, which Pokémon should I teach\n"
	.string "Double-Edge?$"

MoveTutor_Text_DoubleEdgeTaught: @ 82C7CC8
	.string "I won't live for love anymore!\n"
	.string "I'll become tough!$"

MoveTutor_Text_ExplosionTeach: @ 82C7CFA
	.string "I don't intend to be going nowhere\n"
	.string "fast in the sticks like this forever.\p"
	.string "You watch me, I'll get out to the city\n"
	.string "and become a huge hit.\p"
	.string "Seriously, I'm going to cause\n"
	.string "a huge Explosion of popularity!\p"
	.string "If you overheard that, I'll happily\n"
	.string "give you this TM for your Pokémon!$"

MoveTutor_Text_ExplosionTaught: @ 82C7E7A
	.string "For a long time, I've taught Pokémon\n"
	.string "how to use Explosion, but I've yet\l"
	.string "to ignite my own Explosion…\p"
	.string "Maybe it's because deep down,\n"
	.string "I would rather stay here…$"
	
MoveTutor_Text_NoHeartScale:
	.string "Oh, that's disappointing.\p"
	.string "You dont have any Heart\n"
	.string "Scale.$"
